blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/KevOneRedOne/Simplistic-Tetris/discussions
    about: Ask questions and discuss ideas
  - name: â˜• Buy Me a Coffee
    url: https://buymeacoffee.com/kevoneredone
    about: Support the project with a coffee
  - name: ğŸ› Report an Issue
    url: https://github.com/KevOneRedOne/Simplistic-Tetris/issues/new/choose
    about: Report bugs or request features

